apiVersion: v1
kind: Secret
metadata:
  name: {{ include "spring-boot-api.fullname" . }}-secret
  labels:
    {{- include "spring-boot-api.labels" . | nindent 4 }}
type: Opaque
data:
  API_KEY: {{ randAlphaNum 20 | b64enc | quote }}
  DB_PASSWORD: {{ randAlphaNum 16 | b64enc | quote }}
